user:
  user-name: dev
  age: 22
  sex: man
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_test?useUnicode=true&autoReconnect=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
      max-connections: 10
      idle-timeout: 30000
    user: admin
    password: admin
#达梦
#spring:
#  datasource:
#    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://localhost:5236/SYSDBA?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#    username: SYSDBA
#    password: 123456789


mybatis:
  type-aliases-package: com.example.springbootdemo.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

user-config:
    true

#开启gzip压缩，用于文件传输
server:
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048


